import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryan @ Konbini - À propos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Apprenez en plus sur{" "}
          <a href="https://ryan-pina.com/" target={"_blank"}>
            moi !
          </a>
        </h1>

        <p className={styles.description}>
          Nous nous trouvons ici dans la page{" "}
          <code className={styles.code}>about.js</code>
        </p>

        <div className={styles.grid}>
          <a
            href="https://ryan-pina.com/"
            className={styles.card}
            target={"_blank"}
          >
            <h2>Mon portfolio &rarr;</h2>
            <p>Consultez mon portfolio !</p>
          </a>

          <Link href="/social">
            <a className={styles.card}>
              <h2>Mes réseaux &rarr;</h2> <p>Vous me recherchez ?</p>
            </a>
          </Link>

          <Link href="/">
            <a className={styles.card}>
              <h2>Home &rarr;</h2> <p>Pour retourner à l'accueil.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
