import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../src/components/button";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryan @ Konbini - Ma découverte de Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Je m'en vais à la découverte de{" "}
          <a href="https://nextjs.org">Next.js !</a>
        </h1>

        <p className={styles.description}>
          Il s'agit ici de la page <code className={styles.code}>index.js</code>{" "}
          que je vais m'amuser à éditer.
        </p>

        <div className={styles.grid}>
          <Button
            value={"À propos"}
            title="Apprenez en davantage sur moi ainsi que ma formation."
            onClick={"/about"}
          />

          <Button
            value={"Bac à sable"}
            title="Allons nous exercer au Javascript."
            onClick={"/test"}
          />
        </div>
      </main>

      <footer
        className={styles.footer}
        style={{
          backgroundColor: "red",
        }}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
