import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryan @ Konbini - Réseaux sociaux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Où me retrouver <a href="https://nextjs.org">?</a>
        </h1>

        <p className={styles.description}>
          Au sein de cette page <code className={styles.code}>social.js</code>{" "}
          vous pourrez trouver mes différents réseaux sociaux.
        </p>

        <div className={styles.grid}>
          <Link href="about">
            <a className={styles.card}>
              <h2>GitHub &rarr;</h2> <p>Pour jeter un oeil à mes projets.</p>
            </a>
          </Link>

          <a
            href="https://nextjs.org/docs/getting-started"
            className={styles.card}
            target="blank"
          >
            <h2>LinkedIn &rarr;</h2>
            <p>Pour me contacter et pourquoi pas discuter.</p>
          </a>

          <a
            href="https://www.konbini.com/"
            className={styles.card}
            target="blank"
          >
            <h2>Netlify &rarr;</h2>
            <p>Interagissez avec mes applications.</p>
          </a>

          <Link href="/">
            <a className={styles.card}>
              <h2>Home &rarr;</h2> <p>Pour retourner à l'accueil.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
