import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import DateExo from "../src/components/profil/DateExo";
import Infos from "../src/components/profil/Infos";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryan @ Konbini - Page de test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Exerçons nous <a href="https://nextjs.org">!</a>
        </h1>
        <p className={styles.description}>
          Sur cette page <code className={styles.code}>test.js</code>, nous
          pourrons tester nos différents composants React.
        </p>
        <p className={styles.description}>
          Par exemple, le bloc ci-dessous nous donne la date du jour.
        </p>
        <DateExo />
        <Infos />

        <div className={styles.grid}>
          <p className={styles.description}>
            Ces deux boutons quant à eux, redirigent vers mes réseaux sociaux.
          </p>
          <a
            href="https://github.com/N95Ryan"
            className={styles.card}
            target="blank"
          >
            <h2>Mon GitHub</h2>
          </a>
          <a
            href="https://www.linkedin.com/in/ryan-pina-silasse/"
            className={styles.card}
            target="blank"
          >
            <h2>Ma page LinkedIn</h2>
          </a>
        </div>
        <div className={styles.grid}>
          <Link href="/">
            <a className={styles.card}>
              <h2>Home &rarr;</h2> <p>Retourner à l'accueil.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer
        className={styles.footer}
        style={{
          backgroundColor: "green",
        }}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
